### ISSUE TITLE
toggleframe.js did not work for me

### ISSUE THREAD

**Issue by robbycbennett** [sean-codes/atom-windows-titlebar#12]
It has worked for me before. Today I opened up Atom and the title bar was back. I followed the instructions again to toggle the bar. The command line said that it toggled it to false, then I opened Atom. The title bar is still there.

**Comment by sean-codes** [comment]
Hi! I'm not on windows anymore but found a PC to test this out on for you. The first time I ran the script it seemed to fail because I had atom opened. The second time it failed because I opened atom up before the script was completely finished. 

If toggleframe does not work you might need to run it to enable then disable again. Also can you make sure your running it in the right version folder. Check your atom version in "About atom" and match that version up with your folder

```bash
canyon@DESKTOP-UCTB4EQ MINGW64 ~/AppData/Local/atom/app-1.46.0
$ node toggleframe.js
Unpacking ASAR...
Toggling Frame...false
Repacking ASAR...
done! Reopen Atom!

canyon@DESKTOP-UCTB4EQ MINGW64 ~/AppData/Local/atom/app-1.46.0
```

**Comment by robbycbennett** [comment]
Yeah, that works for me. I realized I had to wait until the prompt returned for it to be permanent. If I opened it when it said "done! Reopen Atom!" then it would just work for that one time.
